import { useEffect, useRef, useState } from "react";
import { Link } from "react-router";
import { getImageUrl } from "@/lib/get-image-url";
import type { BannerSlide } from "@/lib/api/storefront-settings";

type BannerCarouselProps = {
  slides: BannerSlide[];
  autoPlayMs?: number;
};

// Minimum horizontal drag distance (px) before a touch gesture counts as a swipe.
const SWIPE_THRESHOLD = 40;

// Responsive widths generated by ImageKit.
// The browser chooses the closest appropriate image based on viewport width.
const BANNER_WIDTHS = [480, 768, 1024, 1280, 1600];

export function BannerCarousel({
  slides,
  autoPlayMs = 5000,
}: BannerCarouselProps) {
  const [index, setIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false);

  const touchStartX = useRef<number | null>(null);
  const touchDeltaX = useRef(0);
  const prefersReducedMotion = useRef(false);

  const hasMultiple = slides.length > 1;

  useEffect(() => {
    prefersReducedMotion.current = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;
  }, []);

  useEffect(() => {
    if (!hasMultiple || isPaused || prefersReducedMotion.current) {
      return;
    }

    const timer = window.setInterval(() => {
      setIndex((current) => (current + 1) % slides.length);
    }, autoPlayMs);

    return () => window.clearInterval(timer);
  }, [hasMultiple, isPaused, slides.length, autoPlayMs]);

  function goPrev() {
    setIndex((current) => (current - 1 + slides.length) % slides.length);
  }

  function goNext() {
    setIndex((current) => (current + 1) % slides.length);
  }

  function handleTouchStart(e: React.TouchEvent<HTMLDivElement>) {
    touchStartX.current = e.touches[0]?.clientX ?? null;
    touchDeltaX.current = 0;
  }

  function handleTouchMove(e: React.TouchEvent<HTMLDivElement>) {
    if (touchStartX.current === null) return;

    const currentX = e.touches[0]?.clientX;

    if (currentX !== undefined) {
      touchDeltaX.current = currentX - touchStartX.current;
    }
  }

  function handleTouchEnd() {
    if (Math.abs(touchDeltaX.current) >= SWIPE_THRESHOLD) {
      if (touchDeltaX.current < 0) {
        goNext();
      } else {
        goPrev();
      }
    }

    touchStartX.current = null;
    touchDeltaX.current = 0;
  }

  if (slides.length === 0) return null;

  const activeSlide = slides[index];

  return (
    <div className="relative left-1/2 w-screen -translate-x-1/2 overflow-hidden">
      <div
        className="relative aspect-[3/2] w-full overflow-hidden sm:aspect-[2/1] lg:aspect-[29/10]"
        role="region"
        aria-roledescription="carousel"
        aria-label="Promotional banners"
        onMouseEnter={() => setIsPaused(true)}
        onMouseLeave={() => setIsPaused(false)}
        onFocus={() => setIsPaused(true)}
        onBlur={() => setIsPaused(false)}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        {slides.map((slide, i) => {
          const srcSet = BANNER_WIDTHS.map(
            (width) =>
              `${getImageUrl(slide.image, {
                width,
                quality: 80,
              })} ${width}w`,
          ).join(", ");

          const optimizedSrc = getImageUrl(slide.image, {
            width: 1600,
            quality: 80,
          });

          const isActive = i === index;
          const isFirst = i === 0;

          return (
            <img
              key={slide.image}
              src={optimizedSrc}
              srcSet={srcSet}
              sizes="100vw"
              width={1600}
              height={552}
              alt=""
              role="group"
              aria-roledescription="slide"
              aria-label={`${i + 1} of ${slides.length}`}
              aria-hidden={!isActive}
              loading={isFirst ? "eager" : "lazy"}
              fetchPriority={isFirst ? "high" : "auto"}
              decoding="async"
              className={`absolute inset-0 size-full object-cover transition-opacity duration-1000 ease-in-out motion-reduce:transition-none ${
                isActive ? "opacity-100" : "opacity-0"
              }`}
            />
          );
        })}

        {/* Overlay button for the active slide, if it has one. A real,
            keyboard-accessible link — not baked into the image. */}
        {activeSlide.buttonLabel && activeSlide.href && (
          <Link
            to={activeSlide.href}
            className="absolute bottom-14 left-4 rounded-full bg-black px-4 py-2 text-sm font-semibold text-white shadow-lg transition-transform hover:scale-105 sm:bottom-16 sm:left-8 sm:px-5 sm:py-2.5 sm:text-base"
          >
            {activeSlide.buttonLabel}
          </Link>
        )}

        <span className="sr-only" aria-live="polite">
          {`Showing banner ${index + 1} of ${slides.length}`}
        </span>

        {hasMultiple && (
          <div
            className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-1.5"
            role="tablist"
            aria-label="Banner navigation"
          >
            {slides.map((_, i) => (
              <button
                key={i}
                type="button"
                onClick={() => setIndex(i)}
                role="tab"
                aria-label={`Go to banner ${i + 1}`}
                aria-selected={i === index}
                className="h-1.5 w-6 origin-left rounded-full bg-white/60 transition-transform duration-300 ease-out focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring motion-reduce:transition-none"
                style={{
                  transform: i === index ? "scaleX(1)" : "scaleX(0.25)",
                }}
              >
                <span
                  className={`block h-full w-full rounded-full transition-colors duration-300 motion-reduce:transition-none ${
                    i === index ? "bg-white" : "bg-transparent"
                  }`}
                />
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}