import { ChevronLeftIcon, ChevronRightIcon } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { getImageUrl } from "@/lib/get-image-url";

type BannerCarouselProps = {
  images: string[];
  autoPlayMs?: number;
};

// Minimum horizontal drag distance (px) before a touch gesture counts as a swipe.
const SWIPE_THRESHOLD = 40;

// Responsive widths generated by ImageKit.
// The browser chooses the closest appropriate image based on viewport width.
const BANNER_WIDTHS = [480, 768, 1024, 1280, 1600];

export function BannerCarousel({
  images,
  autoPlayMs = 5000,
}: BannerCarouselProps) {
  const [index, setIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false);

  const touchStartX = useRef<number | null>(null);
  const touchDeltaX = useRef(0);
  const prefersReducedMotion = useRef(false);

  const hasMultiple = images.length > 1;

  useEffect(() => {
    prefersReducedMotion.current = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;
  }, []);

  useEffect(() => {
    if (!hasMultiple || isPaused || prefersReducedMotion.current) {
      return;
    }

    const timer = window.setInterval(() => {
      setIndex((current) => (current + 1) % images.length);
    }, autoPlayMs);

    return () => window.clearInterval(timer);
  }, [hasMultiple, isPaused, images.length, autoPlayMs]);

  function goPrev() {
    setIndex((current) => (current - 1 + images.length) % images.length);
  }

  function goNext() {
    setIndex((current) => (current + 1) % images.length);
  }

  function handleTouchStart(e: React.TouchEvent<HTMLDivElement>) {
    touchStartX.current = e.touches[0]?.clientX ?? null;
    touchDeltaX.current = 0;
  }

  function handleTouchMove(e: React.TouchEvent<HTMLDivElement>) {
    if (touchStartX.current === null) return;

    const currentX = e.touches[0]?.clientX;

    if (currentX !== undefined) {
      touchDeltaX.current = currentX - touchStartX.current;
    }
  }

  function handleTouchEnd() {
    if (Math.abs(touchDeltaX.current) >= SWIPE_THRESHOLD) {
      if (touchDeltaX.current < 0) {
        goNext();
      } else {
        goPrev();
      }
    }

    touchStartX.current = null;
    touchDeltaX.current = 0;
  }

  if (images.length === 0) return null;

  return (
    <div className="relative left-1/2 w-screen -translate-x-1/2 overflow-hidden">
      <div
        className="relative aspect-[16/7] w-full overflow-hidden sm:aspect-[21/8] md:aspect-[4/1] lg:aspect-[5/1]"
        role="region"
        aria-roledescription="carousel"
        aria-label="Promotional banners"
        onMouseEnter={() => setIsPaused(true)}
        onMouseLeave={() => setIsPaused(false)}
        onFocus={() => setIsPaused(true)}
        onBlur={() => setIsPaused(false)}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        {images.map((src, i) => {
          const srcSet = BANNER_WIDTHS.map(
            (width) =>
              `${getImageUrl(src, {
                width,
                quality: 80,
              })} ${width}w`,
          ).join(", ");

          const optimizedSrc = getImageUrl(src, {
            width: 1280,
            quality: 80,
          });

          const isActive = i === index;
          const isFirst = i === 0;

          return (
            <img
              key={src}
              src={optimizedSrc}
              srcSet={srcSet}
              sizes="100vw"
              width={1600}
              height={640}
              alt=""
              role="group"
              aria-roledescription="slide"
              aria-label={`${i + 1} of ${images.length}`}
              aria-hidden={!isActive}
              loading={isFirst ? "eager" : "lazy"}
              fetchPriority={isFirst ? "high" : "auto"}
              decoding="async"
              className={`absolute inset-0 size-full object-cover transition-opacity duration-700 ease-out motion-reduce:transition-none ${
                isActive ? "opacity-100" : "opacity-0"
              }`}
            />
          );
        })}

        <span className="sr-only" aria-live="polite">
          {`Showing banner ${index + 1} of ${images.length}`}
        </span>

        {hasMultiple && (
          <>
            <button
              type="button"
              onClick={goPrev}
              aria-label="Previous banner"
              className="absolute left-4 top-1/2 -translate-y-1/2 rounded-full bg-white/80 p-2 text-foreground shadow-sm backdrop-blur transition-colors hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
            >
              <ChevronLeftIcon className="size-5" aria-hidden="true" />
            </button>

            <button
              type="button"
              onClick={goNext}
              aria-label="Next banner"
              className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full bg-white/80 p-2 text-foreground shadow-sm backdrop-blur transition-colors hover:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
            >
              <ChevronRightIcon className="size-5" aria-hidden="true" />
            </button>

            <div
              className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-1.5"
              role="tablist"
              aria-label="Banner navigation"
            >
              {images.map((_, i) => (
                <button
                  key={i}
                  type="button"
                  onClick={() => setIndex(i)}
                  role="tab"
                  aria-label={`Go to banner ${i + 1}`}
                  aria-selected={i === index}
                  className="h-1.5 w-6 origin-left rounded-full bg-white/60 transition-transform duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring motion-reduce:transition-none"
                  style={{
                    transform: i === index ? "scaleX(1)" : "scaleX(0.25)",
                  }}
                >
                  <span
                    className={`block h-full w-full rounded-full transition-colors motion-reduce:transition-none ${
                      i === index ? "bg-white" : "bg-transparent"
                    }`}
                  />
                </button>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}